"""empty message

Revision ID: 1e6cd9fede80
Revises: 66092e05b090
Create Date: 2024-08-26 23:34:30.430546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e6cd9fede80'
down_revision = '66092e05b090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(length=50), nullable=False),
    sa.Column('companyMail', sa.String(length=254), nullable=False),
    sa.Column('companyPhone', sa.Integer(), nullable=False),
    sa.Column('companyAdress', sa.String(length=254), nullable=False),
    sa.Column('companyIdentification', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('companyId'),
    sa.UniqueConstraint('companyMail'),
    sa.UniqueConstraint('companyName'),
    sa.UniqueConstraint('companyPhone')
    )
    op.create_table('administrator',
    sa.Column('administratorId', sa.Integer(), nullable=False),
    sa.Column('administratorName', sa.String(length=50), nullable=False),
    sa.Column('administratorLastName', sa.String(length=50), nullable=False),
    sa.Column('administratorPosition', sa.String(length=60), nullable=False),
    sa.Column('administratorMail', sa.String(length=254), nullable=False),
    sa.Column('administratorPhone', sa.Integer(), nullable=False),
    sa.Column('administratorAdress', sa.String(length=254), nullable=False),
    sa.Column('administratorIdentification', sa.Integer(), nullable=False),
    sa.Column('administratorUsername', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['administratorUsername'], ['user.username'], ),
    sa.PrimaryKeyConstraint('administratorId'),
    sa.UniqueConstraint('administratorMail'),
    sa.UniqueConstraint('administratorPhone'),
    sa.UniqueConstraint('administratorUsername')
    )
    op.create_table('supervisor',
    sa.Column('supervisorId', sa.Integer(), nullable=False),
    sa.Column('supervisorName', sa.String(length=50), nullable=False),
    sa.Column('supervisorLastName', sa.String(length=50), nullable=False),
    sa.Column('supervisorPosition', sa.String(length=60), nullable=False),
    sa.Column('supervisorMail', sa.String(length=254), nullable=False),
    sa.Column('supervisorPhone', sa.Integer(), nullable=False),
    sa.Column('supervisorAdress', sa.String(length=254), nullable=False),
    sa.Column('supervisorIdentification', sa.Integer(), nullable=False),
    sa.Column('supervisorUsername', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['supervisorUsername'], ['user.username'], ),
    sa.PrimaryKeyConstraint('supervisorId'),
    sa.UniqueConstraint('supervisorMail'),
    sa.UniqueConstraint('supervisorPhone'),
    sa.UniqueConstraint('supervisorUsername')
    )
    op.create_table('worker',
    sa.Column('workerId', sa.Integer(), nullable=False),
    sa.Column('workerName', sa.String(length=50), nullable=False),
    sa.Column('workerLastName', sa.String(length=50), nullable=False),
    sa.Column('workerPosition', sa.String(length=60), nullable=False),
    sa.Column('workerMail', sa.String(length=254), nullable=False),
    sa.Column('workerPhone', sa.Integer(), nullable=False),
    sa.Column('workerAdress', sa.String(length=254), nullable=False),
    sa.Column('workerIdentification', sa.Integer(), nullable=False),
    sa.Column('workerUsername', sa.String(length=16), nullable=False),
    sa.Column('workerPerformance', sa.String(length=254), nullable=False),
    sa.ForeignKeyConstraint(['workerUsername'], ['user.username'], ),
    sa.PrimaryKeyConstraint('workerId'),
    sa.UniqueConstraint('workerMail'),
    sa.UniqueConstraint('workerPhone'),
    sa.UniqueConstraint('workerUsername')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker')
    op.drop_table('supervisor')
    op.drop_table('administrator')
    op.drop_table('company')
    # ### end Alembic commands ###
