"""empty message

Revision ID: 2956291eaf19
Revises: a4912e4283c5
Create Date: 2024-08-26 23:55:34.563688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2956291eaf19'
down_revision = 'a4912e4283c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue',
    sa.Column('issueId', sa.Integer(), nullable=False),
    sa.Column('issueName', sa.String(length=50), nullable=False),
    sa.Column('issueDesc', sa.String(), nullable=False),
    sa.Column('issueProof', sa.String(), nullable=False),
    sa.Column('issueReview', sa.String(), nullable=True),
    sa.Column('issueStatus', sa.String(), nullable=False),
    sa.Column('issueAdminId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['issueAdminId'], ['administrator.administratorId'], ),
    sa.PrimaryKeyConstraint('issueId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('issue')
    # ### end Alembic commands ###
