"""empty message

Revision ID: 5f2c97ecf6ba
Revises: 8a5dd0c2e243
Create Date: 2024-08-27 00:21:49.439097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2c97ecf6ba'
down_revision = '8a5dd0c2e243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issueSupervisorId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'supervisor', ['issueSupervisorId'], ['supervisorId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('issueSupervisorId')

    # ### end Alembic commands ###
