"""empty message

Revision ID: 66092e05b090
Revises: df6c7c169419
Create Date: 2024-08-26 23:34:02.846235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66092e05b090'
down_revision = 'df6c7c169419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('roleName', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('roleId'),
    sa.UniqueConstraint('roleName')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('userPassword', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('userPic', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('userRoleId', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['username'])
        batch_op.create_unique_constraint(None, ['userPassword'])
        batch_op.create_unique_constraint(None, ['userPic'])
        batch_op.create_foreign_key(None, 'role', ['userRoleId'], ['roleId'])
        batch_op.drop_column('password')
        batch_op.drop_column('email')
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.drop_column('userRoleId')
        batch_op.drop_column('userPic')
        batch_op.drop_column('userPassword')
        batch_op.drop_column('username')
        batch_op.drop_column('userId')

    op.drop_table('role')
    # ### end Alembic commands ###
