"""empty message

Revision ID: 8a5dd0c2e243
Revises: 2956291eaf19
Create Date: 2024-08-27 00:20:28.291487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5dd0c2e243'
down_revision = '2956291eaf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issueWorkerId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'worker', ['issueWorkerId'], ['workerId'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('issueWorkerId')

    # ### end Alembic commands ###
