"""empty message

Revision ID: a4912e4283c5
Revises: 1e6cd9fede80
Create Date: 2024-08-26 23:35:07.499207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4912e4283c5'
down_revision = '1e6cd9fede80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('taskId', sa.Integer(), nullable=False),
    sa.Column('taskName', sa.String(length=50), nullable=False),
    sa.Column('taskDesc', sa.String(), nullable=False),
    sa.Column('taskProof', sa.String(), nullable=False),
    sa.Column('taskReview', sa.String(length=254), nullable=True),
    sa.Column('taskStatus', sa.String(length=254), nullable=False),
    sa.Column('taskWorkerId', sa.Integer(), nullable=False),
    sa.Column('taskSupervisorId', sa.Integer(), nullable=False),
    sa.Column('taskCompany', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['taskCompany'], ['company.companyName'], ),
    sa.ForeignKeyConstraint(['taskSupervisorId'], ['supervisor.supervisorId'], ),
    sa.ForeignKeyConstraint(['taskWorkerId'], ['worker.workerId'], ),
    sa.PrimaryKeyConstraint('taskId'),
    sa.UniqueConstraint('taskCompany')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
