"""empty message

Revision ID: d779eefce712
Revises: 5f2c97ecf6ba
Create Date: 2024-08-27 00:22:41.132839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd779eefce712'
down_revision = '5f2c97ecf6ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.alter_column('issueWorkerId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue', schema=None) as batch_op:
        batch_op.alter_column('issueWorkerId',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
