"""empty message

Revision ID: f0622259f456
Revises: 
Create Date: 2024-08-29 02:25:06.236706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0622259f456'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('companyId', sa.Integer(), nullable=False),
    sa.Column('companyName', sa.String(length=50), nullable=False),
    sa.Column('companyMail', sa.String(length=254), nullable=False),
    sa.Column('companyPhone', sa.Integer(), nullable=False),
    sa.Column('companyAdress', sa.String(length=254), nullable=False),
    sa.Column('companyIdentification', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('companyId'),
    sa.UniqueConstraint('companyMail'),
    sa.UniqueConstraint('companyName'),
    sa.UniqueConstraint('companyPhone')
    )
    op.create_table('role',
    sa.Column('roleId', sa.Integer(), nullable=False),
    sa.Column('roleName', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('roleId'),
    sa.UniqueConstraint('roleName')
    )
    op.create_table('user',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('userPassword', sa.String(length=256), nullable=False),
    sa.Column('userSalt', sa.String(length=256), nullable=False),
    sa.Column('userPic', sa.String(length=256), nullable=False),
    sa.Column('userRoleId', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['userRoleId'], ['role.roleId'], ),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('userPassword'),
    sa.UniqueConstraint('userPic'),
    sa.UniqueConstraint('userSalt'),
    sa.UniqueConstraint('username')
    )
    op.create_table('administrator',
    sa.Column('administratorId', sa.Integer(), nullable=False),
    sa.Column('administratorName', sa.String(length=50), nullable=False),
    sa.Column('administratorLastName', sa.String(length=50), nullable=False),
    sa.Column('administratorPosition', sa.String(length=60), nullable=False),
    sa.Column('administratorMail', sa.String(length=254), nullable=False),
    sa.Column('administratorPhone', sa.Integer(), nullable=False),
    sa.Column('administratorAdress', sa.String(length=254), nullable=False),
    sa.Column('administratorIdentification', sa.Integer(), nullable=False),
    sa.Column('administratorUsername', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['administratorUsername'], ['user.username'], ),
    sa.PrimaryKeyConstraint('administratorId'),
    sa.UniqueConstraint('administratorMail'),
    sa.UniqueConstraint('administratorPhone'),
    sa.UniqueConstraint('administratorUsername')
    )
    op.create_table('supervisor',
    sa.Column('supervisorId', sa.Integer(), nullable=False),
    sa.Column('supervisorName', sa.String(length=50), nullable=False),
    sa.Column('supervisorLastName', sa.String(length=50), nullable=False),
    sa.Column('supervisorPosition', sa.String(length=60), nullable=False),
    sa.Column('supervisorMail', sa.String(length=254), nullable=False),
    sa.Column('supervisorPhone', sa.Integer(), nullable=False),
    sa.Column('supervisorAdress', sa.String(length=254), nullable=False),
    sa.Column('supervisorIdentification', sa.Integer(), nullable=False),
    sa.Column('supervisorUsername', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['supervisorUsername'], ['user.username'], ),
    sa.PrimaryKeyConstraint('supervisorId'),
    sa.UniqueConstraint('supervisorMail'),
    sa.UniqueConstraint('supervisorPhone'),
    sa.UniqueConstraint('supervisorUsername')
    )
    op.create_table('worker',
    sa.Column('workerId', sa.Integer(), nullable=False),
    sa.Column('workerName', sa.String(length=50), nullable=False),
    sa.Column('workerLastName', sa.String(length=50), nullable=False),
    sa.Column('workerPosition', sa.String(length=60), nullable=False),
    sa.Column('workerMail', sa.String(length=254), nullable=False),
    sa.Column('workerPhone', sa.Integer(), nullable=False),
    sa.Column('workerAdress', sa.String(length=254), nullable=False),
    sa.Column('workerIdentification', sa.Integer(), nullable=False),
    sa.Column('workerUsername', sa.String(length=16), nullable=False),
    sa.Column('workerPerformance', sa.String(length=254), nullable=False),
    sa.ForeignKeyConstraint(['workerUsername'], ['user.username'], ),
    sa.PrimaryKeyConstraint('workerId'),
    sa.UniqueConstraint('workerMail'),
    sa.UniqueConstraint('workerPhone'),
    sa.UniqueConstraint('workerUsername')
    )
    op.create_table('issue',
    sa.Column('issueId', sa.Integer(), nullable=False),
    sa.Column('issueName', sa.String(length=50), nullable=False),
    sa.Column('issueDesc', sa.String(), nullable=False),
    sa.Column('issueProof', sa.String(), nullable=False),
    sa.Column('issueReview', sa.String(), nullable=True),
    sa.Column('issueStatus', sa.String(), nullable=False),
    sa.Column('issueAdminId', sa.Integer(), nullable=False),
    sa.Column('issueWorkerId', sa.Integer(), nullable=True),
    sa.Column('issueSupervisorId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['issueAdminId'], ['administrator.administratorId'], ),
    sa.ForeignKeyConstraint(['issueSupervisorId'], ['supervisor.supervisorId'], ),
    sa.ForeignKeyConstraint(['issueWorkerId'], ['worker.workerId'], ),
    sa.PrimaryKeyConstraint('issueId')
    )
    op.create_table('task',
    sa.Column('taskId', sa.Integer(), nullable=False),
    sa.Column('taskName', sa.String(length=50), nullable=False),
    sa.Column('taskDesc', sa.String(), nullable=False),
    sa.Column('taskProof', sa.String(), nullable=False),
    sa.Column('taskReview', sa.String(length=254), nullable=True),
    sa.Column('taskStatus', sa.String(length=254), nullable=False),
    sa.Column('taskWorkerId', sa.Integer(), nullable=False),
    sa.Column('taskSupervisorId', sa.Integer(), nullable=False),
    sa.Column('taskCompany', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['taskCompany'], ['company.companyName'], ),
    sa.ForeignKeyConstraint(['taskSupervisorId'], ['supervisor.supervisorId'], ),
    sa.ForeignKeyConstraint(['taskWorkerId'], ['worker.workerId'], ),
    sa.PrimaryKeyConstraint('taskId'),
    sa.UniqueConstraint('taskCompany')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('issue')
    op.drop_table('worker')
    op.drop_table('supervisor')
    op.drop_table('administrator')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('company')
    # ### end Alembic commands ###
